version: "3"

services:

  rails:
    build:
      context: .
      dockerfile: df-rails.dockerfile
    volumes:
      - .:/usr/src/app
    ports:
      - "3000:3000"
    links:
      - database:database

  database:
    build:
      context: .
      dockerfile: df-database.dockerfile
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres: